# Generated by Django 5.1.6 on 2025-02-20 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='eshop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Model Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('dimensions', models.CharField(max_length=100, verbose_name='Dimensions (W x H x D in mm):')),
                ('country_of_origin', models.CharField(max_length=100)),
                ('rated_output_power', models.CharField(blank=True, max_length=50, null=True)),
                ('rated_output_current', models.CharField(blank=True, max_length=50, null=True)),
                ('input_voltage', models.CharField(blank=True, max_length=50, null=True)),
                ('input_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('output_voltage', models.CharField(blank=True, max_length=50, null=True)),
                ('output_frequency_range', models.CharField(blank=True, max_length=50, null=True)),
                ('plc_input', models.CharField(blank=True, max_length=50, null=True, verbose_name='Input')),
                ('plc_output', models.CharField(blank=True, max_length=50, null=True, verbose_name='Output')),
                ('supply_voltage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Supply Voltage')),
                ('output_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Output Type')),
                ('compatible_modules', models.CharField(blank=True, max_length=255, null=True, verbose_name='Compatible Modules')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.category')),
                ('related_products', models.ManyToManyField(blank=True, related_name='linked_products', to='eshop.product')),
            ],
        ),
    ]
