# Generated by Django 5.1.6 on 2025-02-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compatible_modules',
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_modules',
            field=models.ManyToManyField(blank=True, related_name='plc_compatible_with', to='eshop.product'),
        ),
    ]
