# Generated by Django 5.1.6 on 2025-02-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_alter_product_built_in_interface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('X', 'Canceled'), ('D', 'Delivered')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
